var dict_strange_county = {
    'ZA':'DUBLIN',
    'ZB':'CAVAN',
    'ZC':'CARLOW',
    'ZD':'KERRY',
    'ZG':'WICKLOW',
    'ZH':'CLARE',
    'ZF':'KILDARE',
    'ZI':'CORK',
    'ZJ':'DONEGAL',
    'ZK':'GALWAY',
    'ZL':'WESTMEATH',
    'ZO':'WEXFORD',
    'ZP':'LONGFORD',
    'ZR':'LIMERICK',
    'ZS':'MAYO',
    'ZT':'MEATH',
    'ZU':'MONAGHAN',
    'ZV':'WATERFORD',
    'ZW':'ROSCOMMON',
    'ZX':'SLIGO',
    'ZY':'TIPPERARY',
}
module.exports = dict_strange_county;