var dict_counties_Geo = {
    "ANTRIM": {},
    "ARMAGH": {},
    "CARLOW": {},
    "CAVAN": {},
    "CLARE": {},
    "CORK": {},
    "DERRY": {},
    "DONEGAL": {},
    "DOWN": {},
    "DUBLIN": {},
    "FERMANAGH": {},
    "GALWAY": {},
    "KERRY": {},
    "KILDARE": {},
    "KILKENNY": {},
    "LAOIS": {},
    "LEITRIM": {},
    "LIMERICK": {},
    "LONGFORD": {},
    "LOUTH": {},
    "MAYO": {},
    "MEATH": {},
    "MONAGHAN": {},
    "OFFALY": {},
    "ROSCOMMON": {},
    "SLIGO": {},
    "TIPPERARY": {},
    "TYRONE": {},
    "WATERFORD": {},
    "WESTMEATH": {},
    "WEXFORD": {},
    "WICKLOW": {},
};
module.exports = dict_counties_Geo;