var dict_counties = {
    "ANTRIM": [],
    "ARMAGH": [],
    "CARLOW": [],
    "CAVAN": [],
    "CLARE": [],
    "CORK": [],
    "DERRY": [],
    "DONEGAL": [],
    "DOWN": [],
    "DUBLIN": [],
    "FERMANAGH": [],
    "GALWAY": [],
    "KERRY": [],
    "KILDARE": [],
    "KILKENNY": [],
    "LAOIS": [],
    "LEITRIM": [],
    "LIMERICK": [],
    "LONGFORD": [],
    "LOUTH": [],
    "MAYO": [],
    "MEATH": [],
    "MONAGHAN": [],
    "OFFALY": [],
    "ROSCOMMON": [],
    "SLIGO": [],
    "TIPERARY": [],
    "TYRONE": [],
    "WATERFORD": [],
    "WESTMEATH": [],
    "WEXFORD": [],
    "WICKLOW": [],
    "UNDEFINED": [],
};
module.exports = dict_counties;